spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: 123

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate

application:
  crons:
    setDefaultAvatar: 0 0 0 * * *
    deleteUnwantedPosts: 0 0 0 0 * *